//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarWars.JediFollowing.Web.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public decimal Id { get; set; }
        public decimal PadawannId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LessonDate { get; set; }
        public decimal Value { get; set; }
        public string LessonLabel { get; set; }
    
        public virtual Padawann Padawann { get; set; }
    }
}
