//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarWars.JediFollowing.Web.UI.Models
{
    using System;
    
    public partial class PadawanAverageResult
    {
        public string Name { get; set; }
        public Nullable<decimal> Average { get; set; }
    }
}
